# Generated by Django 4.1.2 on 2022-11-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noquiz', models.CharField(max_length=50)),
                ('evaluation', models.BooleanField()),
                ('intitulequiz', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'quiz',
                'unique_together': {('noquiz', 'evaluation')},
            },
        ),
    ]
