# Generated by Django 4.1.2 on 2022-11-03 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.BooleanField()),
                ('noquestion', models.CharField(max_length=50)),
                ('titrequestion', models.CharField(blank=True, max_length=50, null=True)),
                ('intitulequestion', models.CharField(blank=True, max_length=50, null=True)),
                ('dureequestion', models.TimeField(blank=True, null=True)),
                ('coefquestion', models.IntegerField(blank=True, null=True)),
                ('feedbackquestion', models.CharField(blank=True, max_length=50, null=True)),
                ('bonnereponsequestion', models.IntegerField(blank=True, null=True)),
                ('noquiz', models.OneToOneField(db_column='noquiz', on_delete=django.db.models.deletion.DO_NOTHING, to='cds.quiz')),
            ],
            options={
                'db_table': 'questions',
                'unique_together': {('noquiz', 'evaluation', 'noquestion')},
            },
        ),
    ]
