# Generated by Django 4.1.2 on 2022-11-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cds', '0002_delete_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('noquiz', models.CharField(max_length=50)),
                ('evaluation', models.BooleanField()),
                ('intitulequiz', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'quiz',
                'unique_together': {('noquiz', 'evaluation', 'auto_increment_id')},
            },
        ),
    ]
