# Generated by Django 4.1.2 on 2022-11-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0002_propositionsreponses'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='actif',
            field=models.BooleanField(default=False),
        ),
    ]
