# Generated by Django 4.1.2 on 2022-11-03 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0005_alter_questions_evaluation_alter_questions_noquiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='auto_id_questions',
            new_name='auto_id_question',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='noquiz',
            new_name='auto_id_quiz',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='auto_increment_id',
            new_name='auto_id_quiz',
        ),
        migrations.AlterUniqueTogether(
            name='questions',
            unique_together={('noquestion', 'auto_id_question')},
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together={('noquiz', 'evaluation', 'auto_id_quiz')},
        ),
        migrations.RemoveField(
            model_name='questions',
            name='evaluation',
        ),
    ]
