# Generated by Django 4.1.2 on 2022-11-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0007_alter_quiz_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questions',
            unique_together={('noquestion', 'auto_id_quiz')},
        ),
    ]
