# Generated by Django 4.1.2 on 2022-11-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('codeRole', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nomRole', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
    ]
