# Generated by Django 4.1.2 on 2022-11-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='utilisateur',
            constraint=models.UniqueConstraint(condition=models.Q(('codeRole', 'chef')), fields=('codeRole', 'codeSecteur'), name='unique chef de secteur'),
        ),
    ]
