# Generated by Django 4.1.2 on 2022-11-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metier',
            fields=[
                ('codeMetier', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nomMetier', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'metier',
            },
        ),
    ]
