# Generated by Django 4.1.2 on 2022-11-10 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_utilisateur_unique chef de secteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='codeMetier',
            field=models.ForeignKey(db_column='codeMetier', default='resp_rh', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comptes.metier'),
        ),
    ]
