# Generated by Django 4.1.2 on 2022-11-13 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_alter_utilisateur_codemetier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='codeMetier',
            field=models.ForeignKey(db_column='codeMetier', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comptes.metier'),
        ),
    ]
