# Generated by Django 4.1.2 on 2022-11-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_metier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('codeSecteur', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nomSecteur', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'secteur',
            },
        ),
    ]
