# Generated by Django 4.1.2 on 2022-11-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_secteur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={},
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='matricule',
            field=models.CharField(default='AAAA', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='utilisateur',
            constraint=models.UniqueConstraint(fields=('matricule',), name='unique matricule'),
        ),
    ]
