# Generated by Django 4.1.2 on 2022-11-07 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0005_alter_utilisateur_options_utilisateur_matricule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='codeSecteur',
            field=models.ForeignKey(db_column='codeSecteur', default='MKT', on_delete=django.db.models.deletion.DO_NOTHING, to='comptes.secteur'),
        ),
    ]
