# Generated by Django 4.1.2 on 2022-11-07 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0006_utilisateur_codesecteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='codeMetier',
            field=models.ForeignKey(db_column='codeMetier', default='resp_rh', on_delete=django.db.models.deletion.DO_NOTHING, to='comptes.metier'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='codeRole',
            field=models.ForeignKey(db_column='codeRole', default='admin', on_delete=django.db.models.deletion.DO_NOTHING, to='comptes.role'),
        ),
    ]
