# Generated by Django 4.1.2 on 2022-11-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReponsesChoisies',
            fields=[
                ('auto_id_reponse_choisie', models.AutoField(primary_key=True, serialize=False)),
                ('noquestion', models.IntegerField()),
                ('propRep1', models.BooleanField(default=False)),
                ('propRep2', models.BooleanField(default=False)),
                ('propRep3', models.BooleanField(default=False)),
                ('propRep4', models.BooleanField(default=False)),
                ('propRep5', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'reponseschoisies',
            },
        ),
        migrations.CreateModel(
            name='ReponsesChoisiesv2',
            fields=[
                ('auto_id_reponse_choisie2', models.AutoField(primary_key=True, serialize=False)),
                ('noquestion', models.IntegerField()),
                ('noreponsechoisie', models.IntegerField()),
            ],
            options={
                'db_table': 'reponseschoisiesv2',
            },
        ),
        migrations.CreateModel(
            name='ReponsesChoisiesv3',
            fields=[
                ('auto_id_reponse_choisie3', models.AutoField(primary_key=True, serialize=False)),
                ('noquiz', models.CharField(max_length=50)),
                ('norep1', models.IntegerField(blank=True, null=True)),
                ('norep2', models.IntegerField(blank=True, null=True)),
                ('norep3', models.IntegerField(blank=True, null=True)),
                ('norep4', models.IntegerField(blank=True, null=True)),
                ('norep5', models.IntegerField(blank=True, null=True)),
                ('norep6', models.IntegerField(blank=True, null=True)),
                ('norep7', models.IntegerField(blank=True, null=True)),
                ('norep8', models.IntegerField(blank=True, null=True)),
                ('norep9', models.IntegerField(blank=True, null=True)),
                ('norep10', models.IntegerField(blank=True, null=True)),
                ('norep11', models.IntegerField(blank=True, null=True)),
                ('norep12', models.IntegerField(blank=True, null=True)),
                ('norep13', models.IntegerField(blank=True, null=True)),
                ('norep14', models.IntegerField(blank=True, null=True)),
                ('norep15', models.IntegerField(blank=True, null=True)),
                ('norep16', models.IntegerField(blank=True, null=True)),
                ('norep17', models.IntegerField(blank=True, null=True)),
                ('norep18', models.IntegerField(blank=True, null=True)),
                ('norep19', models.IntegerField(blank=True, null=True)),
                ('norep20', models.IntegerField(blank=True, null=True)),
                ('norep21', models.IntegerField(blank=True, null=True)),
                ('norep22', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reponseschoisiesv3',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('date_vu', models.DateField(blank=True)),
                ('localisation', models.CharField(max_length=30)),
            ],
        ),
    ]
