# Generated by Django 4.1.2 on 2022-11-03 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribuer',
            name='noquiz',
        ),
        migrations.RemoveField(
            model_name='historiquequizcomplete',
            name='matriculecollaborateur',
        ),
        migrations.DeleteModel(
            name='Metier',
        ),
        migrations.RemoveField(
            model_name='participer',
            name='noquiz',
        ),
        migrations.RemoveField(
            model_name='propositionsreponses',
            name='noquiz',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='noquiz',
        ),
        migrations.RemoveField(
            model_name='reponseschoisiecollaborateur',
            name='matriculecollaborateur',
        ),
        migrations.DeleteModel(
            name='Responsablerh',
        ),
        migrations.DeleteModel(
            name='Secteurs',
        ),
        migrations.DeleteModel(
            name='Attribuer',
        ),
        migrations.DeleteModel(
            name='Collaborateur',
        ),
        migrations.DeleteModel(
            name='Historiquequizcomplete',
        ),
        migrations.DeleteModel(
            name='Participer',
        ),
        migrations.DeleteModel(
            name='Propositionsreponses',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='Reponseschoisiecollaborateur',
        ),
    ]
