# Generated by Django 4.1.2 on 2022-11-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponseschoisiesv3',
            name='idCollab',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
