# Generated by Django 4.1.2 on 2022-11-09 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0002_reponseschoisies'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reponseschoisies',
            table='reponseschoisies',
        ),
    ]
