# Generated by Django 4.1.2 on 2022-11-03 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collab', '0002_remove_attribuer_noquiz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('matriculecollaborateur', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nomcollaborateur', models.CharField(blank=True, max_length=50, null=True)),
                ('prenomcollaborateur', models.CharField(blank=True, max_length=50, null=True)),
                ('idconnexioncollaborateur', models.CharField(blank=True, max_length=50, null=True)),
                ('pwdconnexioncollaborateur', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'collaborateur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metier',
            fields=[
                ('codemetier', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nommetier', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'metier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('noquiz', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('evaluation', models.BooleanField()),
                ('intitulequiz', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'quiz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Responsablerh',
            fields=[
                ('matriculeresponsablerh', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nomresponsablerh', models.CharField(blank=True, max_length=50, null=True)),
                ('prenomresponsablerh', models.CharField(blank=True, max_length=50, null=True)),
                ('idconnexionresponsablerh', models.CharField(blank=True, max_length=50, null=True)),
                ('pwdconnexionresponsablerh', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'responsablerh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Secteurs',
            fields=[
                ('codesecteur', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nomsecteur', models.CharField(blank=True, max_length=50, null=True)),
                ('matriculechefsecteur', models.CharField(blank=True, max_length=50, null=True)),
                ('nomchefsecteur', models.CharField(blank=True, max_length=50, null=True)),
                ('prenomchefsecteur', models.CharField(blank=True, max_length=50, null=True)),
                ('idconnexionchefsecteur', models.CharField(blank=True, max_length=50, null=True)),
                ('pwdconnexionchefsecteur', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'secteurs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attribuer',
            fields=[
                ('noquiz', models.OneToOneField(db_column='noquiz', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='collab.quiz')),
                ('evaluation', models.BooleanField()),
                ('dejafaitsecteur', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attribuer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historiquequizcomplete',
            fields=[
                ('matriculecollaborateur', models.OneToOneField(db_column='matriculecollaborateur', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='collab.collaborateur')),
                ('dateheure', models.DateField()),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('evaluation', models.BooleanField()),
            ],
            options={
                'db_table': 'historiquequizcomplete',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participer',
            fields=[
                ('noquiz', models.OneToOneField(db_column='noquiz', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='collab.quiz')),
                ('evaluation', models.BooleanField()),
                ('dejafaitcollaborateur', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'participer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('noquiz', models.OneToOneField(db_column='noquiz', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='collab.quiz')),
                ('evaluation', models.BooleanField()),
                ('noquestion', models.CharField(max_length=50)),
                ('titrequestion', models.CharField(blank=True, max_length=50, null=True)),
                ('intitulequestion', models.CharField(blank=True, max_length=50, null=True)),
                ('dureequestion', models.TimeField(blank=True, null=True)),
                ('coefquestion', models.IntegerField(blank=True, null=True)),
                ('feedbackquestion', models.CharField(blank=True, max_length=50, null=True)),
                ('bonnereponsequestion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propositionsreponses',
            fields=[
                ('noquiz', models.OneToOneField(db_column='noquiz', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='collab.questions')),
                ('evaluation', models.BooleanField()),
                ('noquestion', models.CharField(max_length=50)),
                ('nopropositionrep', models.IntegerField()),
                ('intitulepropositionreponse', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'propositionsreponses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reponseschoisiecollaborateur',
            fields=[
                ('matriculecollaborateur', models.OneToOneField(db_column='matriculecollaborateur', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='collab.historiquequizcomplete')),
                ('dateheure', models.DateField()),
                ('evaluation', models.BooleanField()),
                ('noquestion', models.CharField(max_length=50)),
                ('responsechoisie', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'reponseschoisiecollaborateur',
                'managed': False,
            },
        ),
    ]
