# Generated by Django 4.1.2 on 2022-11-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0003_alter_reponseschoisies_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReponsesChoisies',
        ),
    ]
