# Generated by Django 4.1.2 on 2022-11-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0003_reponseschoisiesv3_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponseschoisiesv3',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
