# Generated by Django 4.1.2 on 2022-11-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0004_reponseschoisiesv3_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reponseschoisiesv3',
            old_name='date',
            new_name='datePassage',
        ),
    ]
