# Generated by Django 4.1.2 on 2022-11-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0004_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metier',
            options={},
        ),
    ]
