# Generated by Django 4.1.2 on 2022-11-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0005_reponseschoisies'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponseschoisies',
            name='propRep5',
            field=models.BooleanField(default=False),
        ),
    ]
