# Generated by Django 4.1.2 on 2022-11-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0006_reponseschoisies_proprep5'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReponsesChoisiesv2',
            fields=[
                ('auto_id_reponse_choisie2', models.AutoField(primary_key=True, serialize=False)),
                ('noquestion', models.IntegerField()),
                ('noreponsechoisie', models.IntegerField()),
            ],
            options={
                'db_table': 'reponseschoisiesv2',
            },
        ),
    ]
