# Generated by Django 4.1.2 on 2022-11-03 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0006_metier_testfredy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metier',
            options={'managed': False},
        ),
    ]
