# Generated by Django 4.1.2 on 2022-11-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0007_alter_metier_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribuer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='collaborateur',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historiquequizcomplete',
            options={},
        ),
        migrations.AlterModelOptions(
            name='metier',
            options={},
        ),
        migrations.AlterModelOptions(
            name='participer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='propositionsreponses',
            options={},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reponseschoisiecollaborateur',
            options={},
        ),
        migrations.AlterModelOptions(
            name='responsablerh',
            options={},
        ),
        migrations.AlterModelOptions(
            name='secteurs',
            options={},
        ),
    ]
