# Generated by Django 4.1.2 on 2022-11-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0007_reponseschoisiesv2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReponsesChoisiesv3',
            fields=[
                ('auto_id_reponse_choisie3', models.AutoField(primary_key=True, serialize=False)),
                ('noquiz', models.CharField(max_length=50)),
                ('norep1', models.IntegerField(blank=True, null=True)),
                ('norep2', models.IntegerField(blank=True, null=True)),
                ('norep3', models.IntegerField(blank=True, null=True)),
                ('norep4', models.IntegerField(blank=True, null=True)),
                ('norep5', models.IntegerField(blank=True, null=True)),
                ('norep6', models.IntegerField(blank=True, null=True)),
                ('norep7', models.IntegerField(blank=True, null=True)),
                ('norep8', models.IntegerField(blank=True, null=True)),
                ('norep9', models.IntegerField(blank=True, null=True)),
                ('norep10', models.IntegerField(blank=True, null=True)),
                ('norep11', models.IntegerField(blank=True, null=True)),
                ('norep12', models.IntegerField(blank=True, null=True)),
                ('norep13', models.IntegerField(blank=True, null=True)),
                ('norep14', models.IntegerField(blank=True, null=True)),
                ('norep15', models.IntegerField(blank=True, null=True)),
                ('norep16', models.IntegerField(blank=True, null=True)),
                ('norep17', models.IntegerField(blank=True, null=True)),
                ('norep18', models.IntegerField(blank=True, null=True)),
                ('norep19', models.IntegerField(blank=True, null=True)),
                ('norep20', models.IntegerField(blank=True, null=True)),
                ('norep21', models.IntegerField(blank=True, null=True)),
                ('norep22', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reponseschoisiesv3',
            },
        ),
    ]
