# Generated by Django 4.1.2 on 2022-11-03 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0008_alter_attribuer_options_alter_collaborateur_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribuer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='collaborateur',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='historiquequizcomplete',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='metier',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='participer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='propositionsreponses',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='reponseschoisiecollaborateur',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='responsablerh',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='secteurs',
            options={'managed': False},
        ),
    ]
