# Generated by Django 4.1.2 on 2022-11-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0009_alter_attribuer_options_alter_collaborateur_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metier',
            options={},
        ),
    ]
